_wandb:
    value:
        cli_version: 0.21.0
        e:
            qq01z0ah1rvgve6vhnzmf7cmbakn5wjt:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "5368709120"
                args:
                    - data_root=../../../data/datasets
                    - gpus=1
                    - model=student_distill
                    - limit_train_batches=0.05
                    - limit_val_batches=0.1
                    - monitor=val_minFDE6
                    - model.target.student_model.decoder=mlp
                    - model.target.teacher_model.decoder=mlp
                codePath: emp_Feature_based_Distillation/train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "279201468416"
                email: mralexander.paulus@gmail.com
                executable: /opt/anaconda3/envs/emp39/bin/python
                git:
                    commit: 3418e1581ca66549f1abc79318e8812a739fdf28
                    remote: https://github.com/AlexTindeche/DeepLeaning-Lab.git
                host: localhost
                memory:
                    total: "38654705664"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/alexanderpaulus/Desktop/UniFreiburg/SS_25/deep_learning_lab/mainProject/repoPlace/DeepLeaning-Lab/emp_Feature_based_Distillation/train.py
                python: CPython 3.9.23
                root: .
                startedAt: "2025-07-25T17:07:02.909494Z"
                writerId: qq01z0ah1rvgve6vhnzmf7cmbakn5wjt
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
            "2":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 63
            "3":
                - 7
                - 13
                - 66
            "4": 3.9.23
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 60
future_steps:
    value: 60
historical_steps:
    value: 50
lr:
    value: 0.001
pretrained:
    value: true
pretrained_weights_student:
    value: null
pretrained_weights_teacher:
    value: /Users/alexanderpaulus/Desktop/UniFreiburg/SS_25/deep_learning_lab/mainProject/repoPlace/DeepLeaning-Lab/emp_Feature_based_Distillation/checkpoints/empm.ckpt
warmup_epochs:
    value: 10
weight_decay:
    value: 0.0001
