_wandb:
    value:
        cli_version: 0.21.0
        e:
            5ltfh1kqo7cdq9pjfz3kqcbx1n8wjbrs:
                args:
                    - data_root=../../../data/datasets
                    - gpus=1
                    - model=student_distill
                    - limit_train_batches=0.05
                    - limit_val_batches=0.1
                    - monitor=val_minFDE6
                codePath: emp_Feature_based_Distillation/train.py
                codePathLocal: train.py
                email: mralexander.paulus@gmail.com
                executable: /opt/anaconda3/envs/emp39/bin/python
                git:
                    commit: 3418e1581ca66549f1abc79318e8812a739fdf28
                    remote: https://github.com/AlexTindeche/DeepLeaning-Lab.git
                host: localhost
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/alexanderpaulus/Desktop/UniFreiburg/SS_25/deep_learning_lab/mainProject/repoPlace/DeepLeaning-Lab/emp_Feature_based_Distillation/train.py
                python: CPython 3.9.23
                root: .
                startedAt: "2025-08-01T15:16:19.712920Z"
                writerId: 5ltfh1kqo7cdq9pjfz3kqcbx1n8wjbrs
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
            "2":
                - 1
                - 9
                - 41
                - 50
            "3":
                - 7
                - 13
                - 66
            "4": 3.9.23
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
