_wandb:
    value:
        cli_version: 0.21.0
        e:
            2pgvmchtajls0a9aa8tqzuaobsmsuggq:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "20401094656"
                args:
                    - data_root=../../../data/datasets
                    - gpus=1
                    - model=student_distill
                    - limit_train_batches=0.01
                    - limit_val_batches=0.02
                    - monitor=val_minFDE6
                    - model.target.decoder=mlp
                codePath: emp_Feature_based_Distillation/train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "290075938816"
                email: mralexander.paulus@gmail.com
                executable: /opt/anaconda3/envs/emp39/bin/python
                git:
                    commit: 986f7aade9cbe8d673cff867fcdf355ff931bea1
                    remote: https://github.com/AlexTindeche/DeepLeaning-Lab.git
                host: localhost
                memory:
                    total: "38654705664"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/alexanderpaulus/Desktop/UniFreiburg/SS_25/deep_learning_lab/mainProject/repoPlace/DeepLeaning-Lab/emp_Feature_based_Distillation/train.py
                python: CPython 3.9.23
                root: .
                startedAt: "2025-07-23T19:33:24.843261Z"
                writerId: 2pgvmchtajls0a9aa8tqzuaobsmsuggq
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
            "2":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 63
            "3":
                - 7
                - 13
                - 66
            "4": 3.9.23
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
